const cards=window.CARDS;const COLS=10,ROWS=8,BACK=78;let LANG='both';
function art(i,rev=false){const c=i%COLS,r=Math.floor(i/COLS);return `<div class="art ${rev?'rev':''}"><div class="sprite" style="left:-${c*100}%;top:-${r*100}%"></div></div>`}
function textPair(zh,en){if(LANG==='zh')return `<p>${zh}</p>`;if(LANG==='en')return `<p class="en">${en}</p>`;return `<p>${zh}</p><p class="en">${en}</p>`}
function getDeck(){let d=[...cards];const m=document.getElementById('deck').value;if(m==='major')d=d.filter(x=>x.arcana==='Major Arcana');if(m==='minor')d=d.filter(x=>x.arcana==='Minor Arcana');return d}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const positions={1:[['现在','Current Energy']],3:[['过去','Past'],['现在','Present'],['未来','Future']],5:[['现状','Situation'],['挑战','Challenge'],['隐藏影响','Hidden Influence'],['建议','Advice'],['发展结果','Likely Outcome']]};
const focusZh={general:'综合来看，这组牌反映你目前最重要的能量与趋势。',love:'放在感情里看，这组牌主要反映双方互动、情绪回应与关系发展。',career:'放在事业里看，这组牌主要反映机会、压力、行动与结果。',study:'放在学业里看，这组牌主要反映专注度、学习状态、压力与表现。',money:'放在金钱和现实层面看，这组牌主要反映稳定、安全感、资源与回报。',self:'放在自我成长里看，这组牌主要反映情绪、信念与当前的人生课题。'};
const focusEn={general:'Overall, this spread highlights the most important energies and trends around your situation.',love:'In love, this spread focuses on emotional exchange, connection and relationship development.',career:'In career, this spread focuses on opportunity, pressure, action and direction.',study:'In study, this spread focuses on concentration, learning state, pressure and performance.',money:'In money matters, this spread focuses on stability, resources, security and practical returns.',self:'For self-growth, this spread focuses on emotions, beliefs and the lesson you are currently learning.'};
function orientation(c,rev){return rev?{zhk:c.keywords_reversed_zh,enk:c.keywords_reversed,zhm:c.meaning_reversed_zh,en:c.meaning_reversed,ozh:'逆位',oen:'Reversed'}:{zhk:c.keywords_upright_zh,enk:c.keywords_upright,zhm:c.meaning_upright_zh,en:c.meaning_upright,ozh:'正位',oen:'Upright'}}
function cardBlock(c,rev,pos,i){const o=orientation(c,rev);return `<article class="draw">${LANG==='en'?`<div class="pos">${pos[1]}</div>`:LANG==='zh'?`<div class="pos">${pos[0]}</div>`:`<div class="pos">${pos[0]} · ${pos[1]}</div>`}${art(cards.indexOf(c),rev)}<div class="name">${c.title_en}</div><div class="zh">${c.title_zh}</div><div class="ori">${o.ozh} · ${o.oen}</div><div class="kw">${LANG==='en'?o.enk:LANG==='zh'?o.zhk:o.zhk+' / '+o.enk}</div></article>`}
function draw(){const n=+document.getElementById('count').value;const revOn=document.getElementById('reverse').checked;const clar=document.getElementById('clarify').checked;const d=shuffle(getDeck()).slice(0,n+(clar?1:0)).map(c=>({c,rev:revOn&&Math.random()<.5}));let ps=[...positions[n]];if(clar)ps.push(['补充牌','Clarifier']);document.getElementById('spread').innerHTML=d.map((x,i)=>cardBlock(x.c,x.rev,ps[i],i)).join('');const q=document.getElementById('question').value.trim();const ctx=document.getElementById('context').value.trim();const focus=document.getElementById('focus').value;document.getElementById('meta').textContent=q||'本次牌阵 Reading';let blocks=`<div class="read"><h3>整体讯息 · Overall</h3>${textPair(focusZh[focus]+(q?' 你问的是：'+q+'。':'')+(ctx?' 背景：'+ctx+'。':''),focusEn[focus]+(q?' Question: '+q+'.':'')+(ctx?' Context: '+ctx+'.':''))}</div>`;d.forEach((x,i)=>{const o=orientation(x.c,x.rev);blocks+=`<div class="read"><h3>${ps[i][0]} · ${ps[i][1]} — ${x.c.title_en} · ${x.c.title_zh}</h3>${textPair(o.zhm,o.en)}<div class="kw">${LANG==='en'?o.enk:LANG==='zh'?o.zhk:o.zhk+' / '+o.enk}</div></div>`});blocks+=`<div class="read"><h3>总结 · Summary</h3>${textPair('把这些牌放在一起看，重点不是把结果当成绝对预言，而是看清现在的模式、阻碍和下一步最值得注意的方向。','Taken together, the cards are best used as a reflection on current patterns, obstacles and the next direction worth noticing, rather than as a fixed prediction.')}</div>`;document.getElementById('result').innerHTML=blocks}
function renderGallery(){const q=document.getElementById('search').value.toLowerCase();const f=document.getElementById('filter').value;document.getElementById('grid').innerHTML=cards.map((c,i)=>({c,i})).filter(x=>(f==='all'||x.c.suit===f||(f==='Major'&&x.c.arcana==='Major Arcana'))&&(`${x.c.title_en} ${x.c.title_zh}`.toLowerCase().includes(q))).map(x=>`<article class="gcard" onclick="downloadCard(${x.i})">${art(x.i)}<div class="name">${x.c.title_en}</div><div class="zh">${x.c.title_zh}</div></article>`).join('')}
function downloadCard(i){const img=new Image();img.onload=()=>{const sx=(i%COLS)*96,sy=Math.floor(i/COLS)*144;const cv=document.createElement('canvas');cv.width=384;cv.height=576;const g=cv.getContext('2d');g.drawImage(img,sx,sy,96,144,0,0,384,576);const a=document.createElement('a');a.href=cv.toDataURL('image/png');a.download=cards[i].title_en.toLowerCase().replace(/[^a-z0-9]+/g,'_')+'.png';a.click()};img.src='tarot_sprite.webp'}
function daily(){const s=new Date().toISOString().slice(0,10);let h=0;for(const ch of s)h=(h*31+ch.charCodeAt(0))>>>0;const i=h%cards.length;const c=cards[i],rev=((h>>2)&1)===1,o=orientation(c,rev);document.getElementById('dailyBox').innerHTML=`<div class="daily"><div>${art(i,rev)}</div><div><h2 style="margin-top:0">${c.title_en} · ${c.title_zh}</h2><div class="ori">${o.ozh} · ${o.oen}</div>${textPair(o.zhm,o.en)}<div class="kw">${LANG==='en'?o.enk:LANG==='zh'?o.zhk:o.zhk+' / '+o.enk}</div></div></div>`}
document.getElementById('draw').onclick=draw;document.getElementById('search').oninput=renderGallery;document.getElementById('filter').onchange=renderGallery;document.getElementById('dailyBtn').onclick=daily;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));['read','gallery','daily'].forEach(id=>document.getElementById(id).classList.toggle('hidden',id!==b.dataset.tab));if(b.dataset.tab==='daily')daily()});document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{LANG=b.dataset.lang;document.querySelectorAll('.lang').forEach(x=>x.classList.toggle('active',x===b));if(document.getElementById('result').innerHTML)draw();renderGallery();daily()});renderGallery();daily();