const major=[
['The Fool','愚人','新的开始、自由、信任、冒险','new beginnings, trust, freedom','新的旅程正在开启。保持开放与好奇，同时留意现实风险。','A new journey is opening. Stay curious while remaining aware of practical risks.'],
['The Magician','魔术师','行动、创造、能力、显化','manifestation, skill, action','你已经拥有推动事情发展的资源与能力，关键在于主动使用它们。','You already have the tools to move this situation forward; the key is using them deliberately.'],
['The High Priestess','女祭司','直觉、秘密、内在智慧','intuition, mystery, inner knowing','有些答案不在表面。相信直觉，并观察没有被说出口的信息。','Some answers are beneath the surface. Trust intuition and notice what is not being said.'],
['The Empress','皇后','丰盛、照顾、创造力、成长','abundance, care, creativity','这是滋养、成长与创造的能量，适合让关系或计划自然发展。','This is nurturing, creative energy that supports natural growth.'],
['The Emperor','皇帝','稳定、结构、权威、界限','structure, authority, stability','清晰的规则、边界和计划会让事情更稳定。','Clear structure, boundaries and planning bring stability.'],
['The Hierophant','教皇','传统、学习、指导、价值观','tradition, learning, guidance','可以从经验、制度、老师或成熟的方法中得到帮助。','Guidance may come from experience, mentors, traditions or established methods.'],
['The Lovers','恋人','爱情、选择、契合、价值一致','love, alignment, choices','这张牌强调真诚连接，也强调做出符合自己价值观的选择。','This card highlights connection and choices that align with your values.'],
['The Chariot','战车','前进、决心、掌控、胜利','determination, direction, victory','保持目标明确并持续行动，事情有明显推进的可能。','Focused, disciplined action can move this forward.'],
['Strength','力量','勇气、温柔、自信、内在力量','courage, compassion, inner power','真正的力量来自耐心、自我控制和温柔的坚定。','Real strength comes from patience, self-mastery and gentle confidence.'],
['The Hermit','隐者','独处、反思、智慧、寻找答案','solitude, wisdom, introspection','先安静下来，你需要的答案更可能来自自己的思考。','Step back and listen inwardly; the answer may come through reflection.'],
['Wheel of Fortune','命运之轮','转变、周期、机会、转折点','change, cycles, turning point','局势正在变化，旧周期结束后会出现新的可能。','The cycle is turning and new possibilities can emerge.'],
['Justice','正义','公平、真相、责任、平衡','fairness, truth, accountability','结果会越来越依赖事实、责任和是否做出公平的选择。','Facts, accountability and fair choices matter strongly here.'],
['The Hanged Man','倒吊人','暂停、放下、换角度、等待','pause, surrender, new perspective','暂停并不等于失败。换一个角度，你会看见之前忽略的东西。','A pause is not failure; a new perspective may reveal what you missed.'],
['Death','死神','结束、转化、重生、新阶段','ending, transformation, rebirth','一个阶段正在结束，为真正的新开始腾出空间。','One chapter is ending to create space for a genuine new beginning.'],
['Temperance','节制','平衡、疗愈、协调、节制','balance, healing, moderation','事情适合慢慢调和，不需要走极端。稳定会比速度更重要。','Balance and gradual adjustment matter more than speed.'],
['The Devil','恶魔','束缚、欲望、依赖、阴影','attachment, desire, shadow','注意什么正在让你失去自由：恐惧、欲望、依赖或执念。','Notice what is limiting your freedom through fear, desire, attachment or obsession.'],
['The Tower','高塔','突变、真相揭露、崩塌、突破','upheaval, revelation, breakthrough','旧结构如果不真实，就可能突然被打破，但也会带来更真实的开始。','An unstable structure may break, creating room for a more truthful beginning.'],
['The Star','星星','希望、疗愈、灵感、恢复','hope, healing, inspiration','希望正在回来，适合恢复信心并重新相信未来。','Hope and healing are returning; allow yourself to trust the future again.'],
['The Moon','月亮','直觉、不确定、梦境、迷雾','intuition, dreams, uncertainty','事情还没有完全明朗，先观察，不要急着下结论。','Not everything is clear yet. Observe carefully and avoid rushing to conclusions.'],
['The Sun','太阳','快乐、成功、清晰、活力','joy, success, vitality','这是很明亮的能量，代表事情更容易被看见、确认并向好的方向发展。','This is bright, visible energy that supports clarity and positive development.'],
['Judgement','审判','觉醒、反思、召唤、重新开始','awakening, reflection, calling','过去的经验正在帮助你做出更成熟的新决定。','Past experience is helping you make a more mature new decision.'],
['The World','世界','完成、圆满、整合、阶段成果','completion, fulfillment, integration','一个重要周期接近完成，你正在进入更完整的新阶段。','An important cycle is completing and a more integrated stage is beginning.']];
const ranks=[['Ace','一'],['Two','二'],['Three','三'],['Four','四'],['Five','五'],['Six','六'],['Seven','七'],['Eight','八'],['Nine','九'],['Ten','十'],['Page','侍从'],['Knight','骑士'],['Queen','皇后'],['King','国王']];
const suits={Wands:['权杖','行动、热情、动力','action, passion, momentum','这张牌强调行动力、勇气与事情推进的速度。','This card emphasizes action, courage and momentum.'],Cups:['圣杯','感情、情绪、关系','emotion, intuition, connection','这张牌强调情绪交流、关系连接与内在感受。','This card emphasizes feelings, relationships and emotional connection.'],Swords:['宝剑','思考、沟通、真相','thought, truth, decision','这张牌强调思考、沟通、决定，以及必须面对的事实。','This card emphasizes thought, communication, decisions and truth.'],Pentacles:['星币','现实、工作、稳定','resources, work, stability','这张牌强调现实基础、工作、金钱、安全感与长期发展。','This card emphasizes practical foundations, work, money, security and long-term growth.']};
const rankMeaning={Ace:['新的机会与起点正在出现。','A new opportunity or beginning is emerging.'],Two:['你正在两个方向、选择或责任之间寻找平衡。','You are balancing two directions, choices or responsibilities.'],Three:['事情开始发展，需要合作、耐心或进一步扩展。','The situation is developing through collaboration, patience or expansion.'],Four:['当前更需要稳定、休息或巩固基础。','Stability, rest or consolidation is important now.'],Five:['这是挑战、冲突或失落的阶段，需要正视压力。','This is a phase of challenge, conflict or loss that needs to be faced.'],Six:['事情正在从困难走向改善，支持与推进逐渐出现。','The situation is moving from difficulty toward improvement and support.'],Seven:['需要评估、坚持，同时分辨哪些选择真正值得投入。','Assess carefully, stay steady and choose what is truly worth your energy.'],Eight:['行动、练习和持续投入会带来明显进展。','Practice and consistent effort can create visible progress.'],Nine:['你已经走了很远，现在需要保护成果并相信自己的能力。','You have come far; protect your progress and trust your ability.'],Ten:['一个周期达到高点或终点，结果正在形成。','A cycle is reaching its peak or conclusion and a result is forming.'],Page:['新的消息、学习机会或好奇心正在开启。','A new message, learning opportunity or curiosity is opening.'],Knight:['事情进入行动阶段，需要勇气、速度或稳定执行。','The situation is moving into action and needs courage or steady execution.'],Queen:['成熟的感受、判断或照顾能力会成为你的优势。','Mature judgment, emotional awareness or care is a strength here.'],King:['你有能力以成熟、稳定和负责的方式处理局势。','You can handle this situation with maturity, stability and responsibility.']};
let cards=major.map(m=>({title_en:m[0],title_zh:m[1],suit:'Major',arcana:'Major Arcana',ku_zh:m[2],ku_en:m[3],mu_zh:m[4],mu_en:m[5]}));
for(const [suit,s] of Object.entries(suits))for(const [rank,rz] of ranks){const rm=rankMeaning[rank];cards.push({title_en:`${rank} of ${suit}`,title_zh:`${s[0]}${rz}`,suit,arcana:'Minor Arcana',ku_zh:`${s[1]}；${rm[0].replace('。','')}`,ku_en:`${s[2]}; ${rm[1].replace('.','')}`,mu_zh:`${rm[0]}${s[3]}`,mu_en:`${rm[1]} ${s[4]}`})}
const COLS=10;let LANG='both';
function art(i,rev=false){const c=i%COLS,r=Math.floor(i/COLS);return `<div class="art ${rev?'rev':''}"><div class="sprite" style="left:-${c*100}%;top:-${r*100}%"></div></div>`}
function textPair(zh,en){if(LANG==='zh')return `<p>${zh}</p>`;if(LANG==='en')return `<p class="en">${en}</p>`;return `<p>${zh}</p><p class="en">${en}</p>`}
function getDeck(){let d=[...cards];const m=document.getElementById('deck').value;if(m==='major')d=d.filter(x=>x.arcana==='Major Arcana');if(m==='minor')d=d.filter(x=>x.arcana==='Minor Arcana');return d}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const positions={1:[['现在','Current Energy']],3:[['过去','Past'],['现在','Present'],['未来','Future']],5:[['现状','Situation'],['挑战','Challenge'],['隐藏影响','Hidden Influence'],['建议','Advice'],['发展结果','Likely Outcome']]};
const focusZh={general:'综合来看，这组牌反映你目前最重要的能量与趋势。',love:'放在感情里看，这组牌主要反映双方互动、情绪回应与关系发展。',career:'放在事业里看，这组牌主要反映机会、压力、行动与结果。',study:'放在学业里看，这组牌主要反映专注度、学习状态、压力与表现。',money:'放在金钱和现实层面看，这组牌主要反映稳定、安全感、资源与回报。',self:'放在自我成长里看，这组牌主要反映情绪、信念与当前的人生课题。'};
const focusEn={general:'Overall, this spread highlights the most important energies and trends around your situation.',love:'In love, this spread focuses on emotional exchange, connection and relationship development.',career:'In career, this spread focuses on opportunity, pressure, action and direction.',study:'In study, this spread focuses on concentration, learning state, pressure and performance.',money:'In money matters, this spread focuses on stability, resources, security and practical returns.',self:'For self-growth, this spread focuses on emotions, beliefs and the lesson you are currently learning.'};
function orientation(c,rev){if(!rev)return{zhk:c.ku_zh,enk:c.ku_en,zhm:c.mu_zh,en:c.mu_en,ozh:'正位',oen:'Upright'};return{zhk:'阻滞、失衡、需要重新调整；'+c.ku_zh,enk:'blocked, imbalanced, needs adjustment; '+c.ku_en,zhm:'逆位表示这股能量可能被压抑、过度使用或暂时无法顺利表达。'+c.mu_zh,en:'Reversed, this energy may be blocked, overused or difficult to express clearly. '+c.mu_en,ozh:'逆位',oen:'Reversed'}}
function cardBlock(c,rev,pos){const o=orientation(c,rev);return `<article class="draw">${LANG==='en'?`<div class="pos">${pos[1]}</div>`:LANG==='zh'?`<div class="pos">${pos[0]}</div>`:`<div class="pos">${pos[0]} · ${pos[1]}</div>`}${art(cards.indexOf(c),rev)}<div class="name">${c.title_en}</div><div class="zh">${c.title_zh}</div><div class="ori">${o.ozh} · ${o.oen}</div><div class="kw">${LANG==='en'?o.enk:LANG==='zh'?o.zhk:o.zhk+' / '+o.enk}</div></article>`}
function draw(){const n=+document.getElementById('count').value,revOn=document.getElementById('reverse').checked,clar=document.getElementById('clarify').checked;const d=shuffle(getDeck()).slice(0,n+(clar?1:0)).map(c=>({c,rev:revOn&&Math.random()<.5}));let ps=[...positions[n]];if(clar)ps.push(['补充牌','Clarifier']);document.getElementById('spread').innerHTML=d.map((x,i)=>cardBlock(x.c,x.rev,ps[i])).join('');const q=document.getElementById('question').value.trim(),ctx=document.getElementById('context').value.trim(),focus=document.getElementById('focus').value;document.getElementById('meta').textContent=q||'本次牌阵 Reading';let blocks=`<div class="read"><h3>整体讯息 · Overall</h3>${textPair(focusZh[focus]+(q?' 你问的是：'+q+'。':'')+(ctx?' 背景：'+ctx+'。':''),focusEn[focus]+(q?' Question: '+q+'.':'')+(ctx?' Context: '+ctx+'.':''))}</div>`;d.forEach((x,i)=>{const o=orientation(x.c,x.rev);blocks+=`<div class="read"><h3>${ps[i][0]} · ${ps[i][1]} — ${x.c.title_en} · ${x.c.title_zh}</h3>${textPair(o.zhm,o.en)}<div class="kw">${LANG==='en'?o.enk:LANG==='zh'?o.zhk:o.zhk+' / '+o.enk}</div></div>`});blocks+=`<div class="read"><h3>总结 · Summary</h3>${textPair('把这些牌放在一起看，重点不是把结果当成绝对预言，而是看清现在的模式、阻碍和下一步最值得注意的方向。','Taken together, use these cards to reflect on present patterns, obstacles and the next direction worth noticing rather than as a fixed prediction.')}</div>`;document.getElementById('result').innerHTML=blocks}
function renderGallery(){const q=document.getElementById('search').value.toLowerCase(),f=document.getElementById('filter').value;document.getElementById('grid').innerHTML=cards.map((c,i)=>({c,i})).filter(x=>(f==='all'||x.c.suit===f||(f==='Major'&&x.c.arcana==='Major Arcana'))&&(`${x.c.title_en} ${x.c.title_zh}`.toLowerCase().includes(q))).map(x=>`<article class="gcard" onclick="downloadCard(${x.i})">${art(x.i)}<div class="name">${x.c.title_en}</div><div class="zh">${x.c.title_zh}</div></article>`).join('')}
function downloadCard(i){const img=new Image();img.onload=()=>{const sx=(i%COLS)*96,sy=Math.floor(i/COLS)*144,cv=document.createElement('canvas');cv.width=384;cv.height=576;cv.getContext('2d').drawImage(img,sx,sy,96,144,0,0,384,576);const a=document.createElement('a');a.href=cv.toDataURL('image/png');a.download=cards[i].title_en.toLowerCase().replace(/[^a-z0-9]+/g,'_')+'.png';a.click()};img.src='tarot_sprite.webp'}
function daily(){const s=new Date().toISOString().slice(0,10);let h=0;for(const ch of s)h=(h*31+ch.charCodeAt(0))>>>0;const i=h%cards.length,c=cards[i],rev=((h>>2)&1)===1,o=orientation(c,rev);document.getElementById('dailyBox').innerHTML=`<div class="daily"><div>${art(i,rev)}</div><div><h2 style="margin-top:0">${c.title_en} · ${c.title_zh}</h2><div class="ori">${o.ozh} · ${o.oen}</div>${textPair(o.zhm,o.en)}<div class="kw">${LANG==='en'?o.enk:LANG==='zh'?o.zhk:o.zhk+' / '+o.enk}</div></div></div>`}
document.getElementById('draw').onclick=draw;document.getElementById('search').oninput=renderGallery;document.getElementById('filter').onchange=renderGallery;document.getElementById('dailyBtn').onclick=daily;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));['read','gallery','daily'].forEach(id=>document.getElementById(id).classList.toggle('hidden',id!==b.dataset.tab));if(b.dataset.tab==='daily')daily()});document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{LANG=b.dataset.lang;document.querySelectorAll('.lang').forEach(x=>x.classList.toggle('active',x===b));if(document.getElementById('result').innerHTML)draw();renderGallery();daily()});renderGallery();daily();